security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        login:
            pattern: ^/api/auth/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/auth/login
                username_path: username
                password_path: password
            custom_authenticators:
                - App\Security\JwtAuthenticator
            entry_point: App\Security\JwtEntryPoint

        api:
            pattern: ^/api/
            stateless: true
            entry_point: App\Security\JwtEntryPoint
            jwt: ~
            custom_authenticators:
                - App\Security\JwtAuthenticator
            provider: app_user_provider
            logout:
                path: api/auth/logout

    access_control:
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }